// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfp7WnYObq7NB6UPqEJCFINQlv4xBlVUA',
    appId: '1:890488015074:android:806bb5acf53e0d4ee3f6bb',
    messagingSenderId: '890488015074',
    projectId: 'prodigenius-7af48',
    storageBucket: 'prodigenius-7af48.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKISHFwzUvv7hE51l0HTDcgNqoM0B8qNg',
    appId: '1:890488015074:web:473e680126a6ea3be3f6bb',
    messagingSenderId: '890488015074',
    projectId: 'prodigenius-7af48',
    authDomain: 'prodigenius-7af48.firebaseapp.com',
    storageBucket: 'prodigenius-7af48.firebasestorage.app',
    measurementId: 'G-WKK0NSK4NW',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBccksonFauDttrVeHH4qVBxXKfES9GjZw',
    appId: '1:890488015074:ios:9652c45332405e31e3f6bb',
    messagingSenderId: '890488015074',
    projectId: 'prodigenius-7af48',
    storageBucket: 'prodigenius-7af48.firebasestorage.app',
    iosBundleId: 'com.example.prodigenius',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBccksonFauDttrVeHH4qVBxXKfES9GjZw',
    appId: '1:890488015074:ios:9652c45332405e31e3f6bb',
    messagingSenderId: '890488015074',
    projectId: 'prodigenius-7af48',
    storageBucket: 'prodigenius-7af48.firebasestorage.app',
    iosBundleId: 'com.example.prodigenius',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKISHFwzUvv7hE51l0HTDcgNqoM0B8qNg',
    appId: '1:890488015074:web:97938257f807ab52e3f6bb',
    messagingSenderId: '890488015074',
    projectId: 'prodigenius-7af48',
    authDomain: 'prodigenius-7af48.firebaseapp.com',
    storageBucket: 'prodigenius-7af48.firebasestorage.app',
    measurementId: 'G-3GF18LJ6WB',
  );

}